# Once phpmyadmin is running at <idp>-pma.<domain>, execute the following
# sql statements to create users and databases ...

CREATE USER 'idbroker'@'%' IDENTIFIED BY '${idbroker_pass}';
GRANT USAGE ON *.* TO 'idbroker'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0
  MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `idbroker`;GRANT SELECT, INSERT, UPDATE, DELETE,
  CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES, CREATE VIEW, EVENT,
  TRIGGER, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE,
  EXECUTE ON `idbroker`.* TO 'idbroker'@'%';

CREATE USER 'pwmanager'@'%' IDENTIFIED BY '${pwmanager_pass}';
GRANT USAGE ON *.* TO 'pwmanager'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0
  MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `pwmanager`;GRANT SELECT, INSERT, UPDATE, DELETE,
  CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES, CREATE VIEW, EVENT,
  TRIGGER, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE,
  EXECUTE ON `pwmanager`.* TO 'pwmanager'@'%';

CREATE USER 'ssp'@'%' IDENTIFIED BY '${ssp_pass}';
GRANT USAGE ON *.* TO 'ssp'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0
  MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `ssp`;GRANT SELECT, INSERT, UPDATE, DELETE,
  CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES, CREATE VIEW, EVENT,
  TRIGGER, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE,
  EXECUTE ON `ssp`.* TO 'ssp'@'%';

CREATE USER 'emailservice'@'%' IDENTIFIED BY '${emailservice_pass}';
GRANT USAGE ON *.* TO 'emailservice'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0
  MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `emailservice`;GRANT SELECT, INSERT, UPDATE, DELETE,
  CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES, CREATE VIEW, EVENT,
  TRIGGER, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE,
  EXECUTE ON `emailservice`.* TO 'emailservice'@'%';
